version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules/
    ports:
      - '8001:8001'
    environment:
      NODE_ENV: development

volumes:
  node_modules:
    external: true
