version: "3.9"

services:
  traefik:
    image: "traefik:3.0.0"
    container_name: "traefik"
    command:
      --api.dashboard=true
      --api.insecure=true
      --providers.docker=true
      --providers.docker.exposedByDefault=false
    ports:
      - "81:80"
      - "8080:8080"
    networks:
      - movies-network
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.docker.network=movies-network
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.rule=Host(`traefik.movies.localhost`)
      - traefik.http.services.traefik.loadBalancer.server.port=80

  front-node:
    build:
      context: front/docker/development/node
    volumes:
      - ./front:/app:rw
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run dev"
    tty: true

  front-node-cli:
    build:
      context: front/docker/development/node
    volumes:
      - ./front:/app

  front:
    build:
      context: front/docker/development/nginx
    volumes:
      - ./front:/app:rw
    networks:
      - movies-network
      - default
    labels:
      - traefik.enable=true
      - traefik.docker.network=movies-network
      - traefik.http.routers.front.entrypoints=http
      - traefik.http.routers.front.rule=Host(`movies.localhost`)
      - traefik.http.services.front.loadBalancer.server.port=80

networks:
  movies-network:
    name: movies-network
